"""update task-to-user relations

Revision ID: c1715a18ca7e
Revises: 66466444db44
Create Date: 2024-08-03 18:42:21.498268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1715a18ca7e'
down_revision: Union[str, None] = '66466444db44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_observer',
        sa.Column('task_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('task_performer',
        sa.Column('task_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.drop_table('task_user')
    op.add_column('task', sa.Column('approver_id', sa.UUID(), nullable=True))
    op.drop_constraint('task_approver_id_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['approver_id'], ['id'])
    op.drop_column('task', 'approver_id_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('approver_id_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_approver_id_id_fkey', 'task', 'user', ['approver_id_id'], ['id'])
    op.drop_column('task', 'approver_id')
    op.create_table('task_user',
        sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_user_task_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='task_user_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', 'user_id', name='task_user_pkey')
    )
    op.drop_table('task_performer')
    op.drop_table('task_observer')
    # ### end Alembic commands ###
