"""update secret

Revision ID: cc8d421db5b5
Revises: a70265312559
Create Date: 2024-07-24 16:23:09.260848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8d421db5b5'
down_revision: Union[str, None] = 'a70265312559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invite_account_id_fkey', 'invite', type_='foreignkey')
    op.create_foreign_key(None, 'invite', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.add_column('secret', sa.Column('hashed_password', sa.LargeBinary(), nullable=False))
    op.drop_constraint('secret_account_id_fkey', 'secret', type_='foreignkey')
    op.drop_constraint('secret_user_id_fkey', 'secret', type_='foreignkey')
    op.create_foreign_key(None, 'secret', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'secret', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'secret', type_='foreignkey')
    op.drop_constraint(None, 'secret', type_='foreignkey')
    op.create_foreign_key('secret_user_id_fkey', 'secret', 'user', ['user_id'], ['id'])
    op.create_foreign_key('secret_account_id_fkey', 'secret', 'account', ['account_id'], ['id'])
    op.drop_column('secret', 'hashed_password')
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.create_foreign_key('invite_account_id_fkey', 'invite', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
