"""create task task_user step

Revision ID: 692cf370168b
Revises: 0d27b423fddf
Create Date: 2024-08-03 16:14:32.292351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692cf370168b'
down_revision: Union[str, None] = '0d27b423fddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('deadline', sa.DateTime(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'ongoing', 'done', 'cancelled', name='taskstatusenum'), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('approver_id_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['approver_id_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('is_complete', sa.Boolean(), nullable=False),
        sa.Column('task_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_user',
        sa.Column('task_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_user')
    op.drop_table('step')
    op.drop_table('task')
    # ### end Alembic commands ###
