"""add position division_position

Revision ID: 0d27b423fddf
Revises: b18525c6da5f
Create Date: 2024-07-30 19:16:18.737563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d27b423fddf'
down_revision: Union[str, None] = 'b18525c6da5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('division_position',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('position_id', sa.UUID(), nullable=False),
        sa.Column('division_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Enum('employee', 'manager', name='roleenum'), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['division_id'], ['division.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('division_position')
    op.drop_table('position')
    # ### end Alembic commands ###
